name: Percy CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: npm install
      - name: Percy Test
        uses: percy/exec-action@master
        with:
          command: "node snapshots.js"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
