name: Percy CI
on: 
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
   branches:
     - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: npm install
      - name: Percy Test
        run: "percy exec -t 200 -- mocha tests/scripts/percy --exit"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
